### ISSUE TITLE
Returns empty results

### ISSUE THREAD

**Issue by aymenitc** [ID29TH/simple-find-lyrics#4]
I guess there is change from Google on some songs..
I appreciate your good work 👍
[Edited]

**Comment by aymenitc** [comment]
![Screenshot_٢٠٢٣٠٤١٨_١٥٠١٢٨_Samsung Internet](https://user-images.githubusercontent.com/76839622/232771131-aa7ee4ed-84c8-49f6-9127-c9de6b0b10b4.jpg)

**Comment by ID29TH** [comment]
You may also need to include the name of the artist.
